# Generated by Django 3.1.1 on 2021-05-20 15:02

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('public', models.BooleanField(default=False)),
                ('subtitle', models.CharField(blank=True, max_length=800, null=True)),
                ('md_file', models.FileField(upload_to=api.models.md_file_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dummies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
